"""empty message

Revision ID: 034d6ee74a60
Revises: a9c7e415e7b5
Create Date: 2018-09-27 10:22:35.483631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034d6ee74a60'
down_revision = 'a9c7e415e7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('referred_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_seller_referred_by'), 'seller', ['referred_by'], unique=False)
    op.create_foreign_key(None, 'seller', 'seller', ['referred_by'], ['id'], initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller', type_='foreignkey')
    op.drop_index(op.f('ix_seller_referred_by'), table_name='seller')
    op.drop_column('seller', 'referred_by')
    # ### end Alembic commands ###
