"""empty message

Revision ID: 071f6f7bb964
Revises: 2b68ca632804
Create Date: 2018-09-27 16:23:07.939038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '071f6f7bb964'
down_revision = '2b68ca632804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_register', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('order', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'paid')
    op.alter_column('notification_register', 'task_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
