"""empty message

Revision ID: 0ff32742b39f
Revises: b78b9da7cc1d
Create Date: 2018-09-06 09:42:12.965230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff32742b39f'
down_revision = 'b78b9da7cc1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('identification', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_user_identification'), 'user', ['identification'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_identification'), table_name='user')
    op.drop_column('user', 'identification')
    # ### end Alembic commands ###
