"""empty message

Revision ID: 1dab885b5839
Revises: 9da89b53a34f
Create Date: 2018-09-13 19:41:16.966761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dab885b5839'
down_revision = '9da89b53a34f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('shipping', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('order', sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'tax')
    op.drop_column('order', 'shipping')
    # ### end Alembic commands ###
