"""empty message

Revision ID: 34e025f202c1
Revises: be0b61ca2bd8
Create Date: 2018-09-03 06:25:57.582908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e025f202c1'
down_revision = 'be0b61ca2bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_client_profile_id'), 'client', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'client', 'profile', ['profile_id'], ['id'], initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_index(op.f('ix_client_profile_id'), table_name='client')
    op.drop_column('client', 'profile_id')
    # ### end Alembic commands ###
