"""empty message

Revision ID: 3b114f479424
Revises: d12c8d40b27a
Create Date: 2018-10-09 14:55:10.781616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b114f479424'
down_revision = 'd12c8d40b27a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_seller_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'seller', ['seller_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.drop_constraint('seller_user_id_fkey', 'seller', type_='foreignkey')
    op.create_foreign_key(None, 'seller', 'user', ['user_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.drop_constraint('task_seller_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'seller', ['seller_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_seller_id_fkey', 'task', 'seller', ['seller_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_constraint(None, 'seller', type_='foreignkey')
    op.create_foreign_key('seller_user_id_fkey', 'seller', 'user', ['user_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_seller_id_fkey', 'order', 'seller', ['seller_id'], ['id'], initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###
