"""empty message

Revision ID: 4a5255ad9085
Revises: c817a8b192c4
Create Date: 2018-09-04 05:25:21.123086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a5255ad9085'
down_revision = 'c817a8b192c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_category_category_id'), 'client_category', ['category_id'], unique=False)
    op.create_index(op.f('ix_client_category_client_id'), 'client_category', ['client_id'], unique=False)
    op.add_column('order', sa.Column('order_number', sa.Integer(), nullable=False))
    op.add_column('seller', sa.Column('comission', sa.Numeric(precision=2, scale=2), nullable=True))
    op.add_column('seller', sa.Column('goal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.alter_column('seller', 'income_from_DS',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.alter_column('seller', 'time_investment',
               existing_type=postgresql.INTERVAL(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'time_investment',
               existing_type=postgresql.INTERVAL(),
               nullable=False)
    op.alter_column('seller', 'income_from_DS',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.drop_column('seller', 'goal')
    op.drop_column('seller', 'comission')
    op.drop_column('order', 'order_number')
    op.drop_index(op.f('ix_client_category_client_id'), table_name='client_category')
    op.drop_index(op.f('ix_client_category_category_id'), table_name='client_category')
    op.drop_table('client_category')
    # ### end Alembic commands ###
