"""empty message

Revision ID: 781461d4d943
Revises: 4a5255ad9085
Create Date: 2018-09-04 05:30:32.630648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781461d4d943'
down_revision = '4a5255ad9085'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total_points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_points', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
