"""empty message

Revision ID: b78b9da7cc1d
Revises: cba69b1a7407
Create Date: 2018-09-06 00:58:58.291856

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b78b9da7cc1d'
down_revision = 'cba69b1a7407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('code', sa.Integer(), nullable=True))
    op.alter_column('task', 'excuted_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('user', 'total_active_points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('total_active_points', sa.NUMERIC(precision=10, scale=0), autoincrement=False, nullable=False))
    op.alter_column('task', 'excuted_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('seller', 'code')
    # ### end Alembic commands ###
