"""empty message

Revision ID: bbcb7203c57a
Revises: 56a86dac2594
Create Date: 2018-09-02 12:13:39.274750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbcb7203c57a'
down_revision = '56a86dac2594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('points', sa.Numeric(precision=10), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_detail_order_id'), 'order_detail', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_detail_product_id'), 'order_detail', ['product_id'], unique=False)
    op.drop_index('ix_order_products_order_id', table_name='order_products')
    op.drop_index('ix_order_products_product_id', table_name='order_products')
    op.drop_index('ix_order_products_user_client_id', table_name='order_products')
    op.drop_table('order_products')
    op.add_column('order', sa.Column('client_id', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('total_points', sa.Numeric(precision=10), nullable=False))
    op.create_index(op.f('ix_order_client_id'), 'order', ['client_id'], unique=False)
    op.create_index(op.f('ix_order_seller_id'), 'order', ['seller_id'], unique=False)
    op.drop_index('ix_order_user_id', table_name='order')
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'seller', ['seller_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'order', 'client', ['client_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_column('order', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_index('ix_order_user_id', 'order', ['user_id'], unique=False)
    op.drop_index(op.f('ix_order_seller_id'), table_name='order')
    op.drop_index(op.f('ix_order_client_id'), table_name='order')
    op.drop_column('order', 'total_points')
    op.drop_column('order', 'seller_id')
    op.drop_column('order', 'client_id')
    op.create_table('order_products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='order_products_order_id_fkey', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='order_products_product_id_fkey', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_client_id'], ['user.id'], name='order_products_user_client_id_fkey', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='order_products_pkey')
    )
    op.create_index('ix_order_products_user_client_id', 'order_products', ['user_client_id'], unique=False)
    op.create_index('ix_order_products_product_id', 'order_products', ['product_id'], unique=False)
    op.create_index('ix_order_products_order_id', 'order_products', ['order_id'], unique=False)
    op.drop_index(op.f('ix_order_detail_product_id'), table_name='order_detail')
    op.drop_index(op.f('ix_order_detail_order_id'), table_name='order_detail')
    op.drop_table('order_detail')
    # ### end Alembic commands ###
