"""empty message

Revision ID: bc088a67e4b8
Revises: 3b114f479424
Create Date: 2018-10-15 14:26:26.123252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc088a67e4b8'
down_revision = '3b114f479424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_user_id_fkey', 'client', type_='foreignkey')
    op.drop_constraint('client_seller_id_fkey', 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'user', ['user_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'client', 'seller', ['seller_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.add_column('content', sa.Column('segment_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_content_segment_id'), 'content', ['segment_id'], unique=False)
    op.create_foreign_key(None, 'content', 'segment', ['segment_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_constraint('referral_referred_id_fkey', 'referral', type_='foreignkey')
    op.drop_constraint('referral_referred_by_id_fkey', 'referral', type_='foreignkey')
    op.create_foreign_key(None, 'referral', 'seller', ['referred_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.create_foreign_key(None, 'referral', 'seller', ['referred_by_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.drop_constraint('seller_referred_by_id_fkey', 'seller', type_='foreignkey')
    op.create_foreign_key(None, 'seller', 'seller', ['referred_by_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.create_index(op.f('ix_task_segment_id'), 'task', ['segment_id'], unique=False)
    op.create_foreign_key(None, 'task', 'segment', ['segment_id'], ['id'], initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_index(op.f('ix_task_segment_id'), table_name='task')
    op.drop_constraint(None, 'seller', type_='foreignkey')
    op.create_foreign_key('seller_referred_by_id_fkey', 'seller', 'seller', ['referred_by_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_constraint(None, 'referral', type_='foreignkey')
    op.drop_constraint(None, 'referral', type_='foreignkey')
    op.create_foreign_key('referral_referred_by_id_fkey', 'referral', 'seller', ['referred_by_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('referral_referred_id_fkey', 'referral', 'seller', ['referred_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_index(op.f('ix_content_segment_id'), table_name='content')
    op.drop_column('content', 'segment_id')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key('client_seller_id_fkey', 'client', 'seller', ['seller_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.create_foreign_key('client_user_id_fkey', 'client', 'user', ['user_id'], ['id'], initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###
