"""empty message

Revision ID: be0b61ca2bd8
Revises: d3358887cf9e
Create Date: 2018-09-02 17:30:16.973516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0b61ca2bd8'
down_revision = 'd3358887cf9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('content', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_content_topic_id'), 'content', ['topic_id'], unique=False)
    op.create_foreign_key(None, 'content', 'topic', ['topic_id'], ['id'], initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_index(op.f('ix_content_topic_id'), table_name='content')
    op.drop_column('content', 'topic_id')
    op.drop_table('topic')
    # ### end Alembic commands ###
