"""empty message

Revision ID: bfcaf66a5487
Revises: dda92a35fcf2
Create Date: 2018-10-15 17:03:30.314388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfcaf66a5487'
down_revision = 'dda92a35fcf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_interaction_user_id', table_name='user_interaction')
    op.drop_constraint('user_interaction_user_id_fkey', 'user_interaction', type_='foreignkey')
    op.drop_column('user_interaction', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interaction', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_interaction_user_id_fkey', 'user_interaction', 'user', ['user_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.create_index('ix_user_interaction_user_id', 'user_interaction', ['user_id'], unique=False)
    # ### end Alembic commands ###
