"""empty message

Revision ID: c817a8b192c4
Revises: fd584542ea33
Create Date: 2018-09-03 14:26:50.053666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c817a8b192c4'
down_revision = 'fd584542ea33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Numeric(precision=10), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['seller.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_client_id'), 'order', ['client_id'], unique=False)
    op.create_index(op.f('ix_order_seller_id'), 'order', ['seller_id'], unique=False)
    op.create_table('order_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('points', sa.Numeric(precision=10), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_detail_order_id'), 'order_detail', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_detail_product_id'), 'order_detail', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_detail_product_id'), table_name='order_detail')
    op.drop_index(op.f('ix_order_detail_order_id'), table_name='order_detail')
    op.drop_table('order_detail')
    op.drop_index(op.f('ix_order_seller_id'), table_name='order')
    op.drop_index(op.f('ix_order_client_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
