"""empty message

Revision ID: d12c8d40b27a
Revises: 071f6f7bb964
Create Date: 2018-10-09 09:56:52.530131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12c8d40b27a'
down_revision = '071f6f7bb964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('order', sa.Column('discount_codes', sa.String(), nullable=True))
    op.add_column('user', sa.Column('staff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'staff')
    op.drop_column('order', 'discount_codes')
    op.drop_column('order', 'discount')
    # ### end Alembic commands ###
