"""empty message

Revision ID: d3358887cf9e
Revises: bbcb7203c57a
Create Date: 2018-09-02 17:28:01.602865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3358887cf9e'
down_revision = 'bbcb7203c57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('media_type', sa.String(), nullable=True))
    op.add_column('content', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.add_column('content', sa.Column('thumbnailUrl', sa.String(), nullable=False))
    op.add_column('content', sa.Column('url', sa.String(), nullable=False))
    op.create_index(op.f('ix_content_profile_id'), 'content', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'content', 'profile', ['profile_id'], ['id'], initially='DEFERRED', deferrable=True)
    op.add_column('order', sa.Column('status', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('order', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('order', 'status')
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_index(op.f('ix_content_profile_id'), table_name='content')
    op.drop_column('content', 'url')
    op.drop_column('content', 'thumbnailUrl')
    op.drop_column('content', 'profile_id')
    op.drop_column('content', 'media_type')
    # ### end Alembic commands ###
