"""empty message

Revision ID: dda92a35fcf2
Revises: bc088a67e4b8
Create Date: 2018-10-15 16:35:41.974153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dda92a35fcf2'
down_revision = 'bc088a67e4b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interaction', sa.Column('extra_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('user_interaction', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_interaction_user_id'), 'user_interaction', ['user_id'], unique=False)
    op.create_foreign_key(None, 'user_interaction', 'user', ['user_id'], ['id'], ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_interaction', type_='foreignkey')
    op.drop_index(op.f('ix_user_interaction_user_id'), table_name='user_interaction')
    op.drop_column('user_interaction', 'user_id')
    op.drop_column('user_interaction', 'extra_info')
    # ### end Alembic commands ###
